name: Update bun.lockb
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
jobs:
  bun-lockb:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - run: bun install
      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add bun.lockb
          git commit --amend --no-edit || true
          git push --force